UiConfig = [
    version: uint,
    active_screen_index: uint,
    ? properties: PropertiesConfig,
    screen_configurations: [0*10 ScreenConfig]
]

ScreenConfig = [
    id: uint,
    type: uint,
    grid: GridSettingsConfig,
    widget_configurations: [* WidgetConfig]
]

GridSettingsConfig = [
    snap_enabled: bool,
    width: uint,
    height: uint,
    spacing_px: uint
]

WidgetConfig = [
    type: uint,
    id: uint,
    position: WidgetPositionConfig,
    size: WidgetSizeConfig,
    ? properties: PropertiesConfig
]

PropertiesConfig = {
    * tstr => PropertyValueType
}

WidgetPositionConfig = [
    x: int,
    y: int
]

WidgetSizeConfig = [
    width: uint,
    height: uint
]

PropertyValueType = int / float / tstr / bool / [* int] / [* tstr] / { * tstr => tstr }
