ARG BASE_IMAGE=ubuntu:24.04
FROM ${BASE_IMAGE}

ARG USERNAME=ubuntu
ARG VNCPASSWD=zephyr
ARG UBUNTU_MIRROR_ARCHIVE=archive.ubuntu.com/ubuntu
ARG UBUNTU_MIRROR_SECURITY=security.ubuntu.com/ubuntu
ARG UBUNTU_MIRROR_PORTS=ports.ubuntu.com/ubuntu-ports

SHELL ["/bin/bash", "-c"]

USER root

RUN <<EOF
    # Set up custom Ubuntu APT mirrors
	pushd /etc/apt/sources.list.d
	cp ubuntu.sources ubuntu.sources.bak
	sed -i "s#archive.ubuntu.com/ubuntu#${UBUNTU_MIRROR_ARCHIVE}#" ubuntu.sources
	sed -i "s#security.ubuntu.com/ubuntu#${UBUNTU_MIRROR_SECURITY}#" ubuntu.sources
	sed -i "s#ports.ubuntu.com/ubuntu-ports#${UBUNTU_MIRROR_PORTS}#" ubuntu.sources
	popd

    # Enable 32-bit package support for x86-64
	if [ "${HOSTTYPE}" = "x86_64" ]; then
		dpkg --add-architecture i386
	fi

    apt-get update -y
    apt-get upgrade -y
    apt-get install -y --no-install-recommends git curl ca-certificates ninja-build gperf \
        ccache dfu-util device-tree-compiler wget \
        python3 python3-dev python3-pip python3-ply python3-venv python3-setuptools python3-tk python-is-python3 \
        xz-utils file make gcc gcc-multilib g++-multilib libsdl1.2-dev libsdl2-dev libmagic1 \
        x11vnc xvfb openbox dos2unix xterm usbutils \
        iproute2 npm socat emacs tree locales

    # Install x86-64 image-specific packages
	if [ "${HOSTTYPE}" = "x86_64" ]; then
		# Mark `python3` as held because APT otherwise tries to remove it during i386
		# package installation.
		apt-mark hold python3 python3-apt

		# Install multi-lib gcc
		apt-get install --no-install-recommends -y \
			gcc-multilib \
			g++-multilib

		# Install 32-bit dependencies
		apt-get install --no-install-recommends -y \
			libc6-dbg:i386 \
			libfuse-dev:i386 \
			libsdl2-dev:i386
	fi

    apt-get install -y sudo

    # Clean up stale packages
	apt-get autoremove --purge -y

	# Clean up local repository
	apt-get clean -y
	rm -rf /var/lib/apt/lists/*

	# Restore original Ubuntu mirrors
	pushd /etc/apt/sources.list.d
	mv -f ubuntu.sources.bak ubuntu.sources
	popd
EOF

RUN npm install -g html-minifier-terser

RUN usermod -aG sudo ${USERNAME}

RUN echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/ubuntu

# Add entrypoint and permissions
ADD entrypoint.sh /home/entrypoint.sh
RUN chmod +x /home/entrypoint.sh
ENTRYPOINT ["/home/entrypoint.sh"]

# Set the locale
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

USER ${USERNAME}

# Configure display
ENV DISPLAY=:0

RUN sudo apt-get update

# VNC password
RUN mkdir -p /home/${USERNAME}/.vnc && \
    x11vnc -storepasswd ${VNCPASSWD} /home/${USERNAME}/.vnc/passwd

RUN mkdir -p /home/${USERNAME}/zephyr/workspace
RUN mkdir -p /home/${USERNAME}/zephyr/workspace/project
RUN mkdir -p /home/${USERNAME}/zephyr/workspace/utilities/

# Setup OpenOCD for ESP32
RUN curl -sL -o /home/${USERNAME}/zephyr/workspace/utilities/openocd.tar.gz \
    https://github.com/espressif/openocd-esp32/releases/download/v0.12.0-esp32-20250707/openocd-esp32-linux-amd64-0.12.0-esp32-20250707.tar.gz
RUN tar -xvzf /home/${USERNAME}/zephyr/workspace/utilities/openocd.tar.gz -C /home/${USERNAME}/zephyr/workspace/utilities

RUN python3 -m venv /home/${USERNAME}/zephyr/.venv

RUN mkdir -p /home/${USERNAME}/zephyr/.venv && \
    python3 -m venv /home/${USERNAME}/zephyr/.venv
RUN echo "source /home/${USERNAME}/zephyr/.venv/bin/activate" >> /home/${USERNAME}/.bashrc && \
    chmod +x /home/${USERNAME}/zephyr/.venv/bin/activate

RUN source /home/${USERNAME}/zephyr/.venv/bin/activate && \
    pip install cmake --upgrade

RUN source /home/${USERNAME}/zephyr/.venv/bin/activate && \
    pip install --upgrade pip && \
    pip install west && \
    pip install zcbor

COPY ./west.yml /home/${USERNAME}/zephyr/workspace/project/west.yml

RUN source /home/${USERNAME}/zephyr/.venv/bin/activate && \
    cd /home/${USERNAME}/zephyr/workspace && \
    west init -l /home/${USERNAME}/zephyr/workspace/project && \
    west update && \
    west zephyr-export && \
    west packages pip --install && \
    west blobs fetch hal_espressif

RUN source /home/${USERNAME}/zephyr/.venv/bin/activate && \
    cd /home/${USERNAME}/zephyr/workspace/zephyr && \
    west sdk install

RUN git clone https://github.com/zephyrproject-rtos/net-tools /home/${USERNAME}/zephyr/net-tools

WORKDIR /home/${USERNAME}/zephyr/workspace/project
CMD ["bash"]
