services:
  zephyr-dev:
    container_name: eerie_leap_round_gauge
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DISPLAY=:0
    volumes:
      - ./:/home/ubuntu/zephyr/workspace/project:cached
      - ${HOME}/.Xauthority:/home/ubuntu/.Xauthority:ro
    ports:
      - "5900:5900"
    tty: true
    privileged: true
    pid: host
