CborUiConfig = [
    version: uint,
    active_screen_group_id: uint,
    ? properties: CborPropertiesConfig,
    screen_configurations: [0*10 CborScreenConfig]
]

CborScreenConfig = [
    id: uint,
    group_id: uint,
    type: uint,
    z_index: int,
    is_visible: bool,
    grid: CborGridSettingsConfig,
    widget_configurations: [* CborWidgetConfig]
]

CborGridSettingsConfig = [
    snap_enabled: bool,
    width: uint,
    height: uint,
    spacing_px: uint
]

CborWidgetConfig = [
    type: uint,
    id: uint,
    position: CborWidgetPositionConfig,
    size: CborWidgetSizeConfig,
    z_index: int,
    ? properties: CborPropertiesConfig,
    bindings: [* CborPropertyBinding]
]

CborPropertyBinding = [
    target: uint,
    channel: uint,
    event_type: uint,
    payload_key: uint,
    direction: uint,
    outbound_event_type: uint,
    has_selector: bool,
    selector_key: uint,
    selector_value: CborPropertyValueType
]

CborPropertiesConfig = {
    * tstr => CborPropertyValueType
}

CborWidgetPositionConfig = [
    x: int,
    y: int
]

CborWidgetSizeConfig = [
    width: uint,
    height: uint
]

CborPropertyValueType = int / float / tstr / bool / [* int] / [* tstr] / { * tstr => tstr }
