# CONFIG_BOOTLOADER_MCUBOOT=y

# Debug
# ==============================================

CONFIG_DEBUG=y
CONFIG_NO_OPTIMIZATIONS=y
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_DEBUG_THREAD_INFO=y
# CONFIG_XTENSA_EXCEPTION_ENTER_GDB=y

# Memory
# ==============================================

# PSRAM config for ESP32-S3-N16R8 board with 8MB Octal SPI SPRAM
CONFIG_ESP_SPIRAM=y
CONFIG_SPIRAM_MODE_OCT=y
# SPIRAM (PSRAM) and SPI Flash are on the same bus,
# when SPIRAM is operating in Octal mode at 80MHz, due to the bug:
# https://github.com/zephyrproject-rtos/zephyr/issues/87938
# SPI Flash fails to initialize
CONFIG_SPIRAM_SPEED_40M=y
# 8MB
CONFIG_ESP_SPIRAM_SIZE=8388608
# 4MB
CONFIG_ESP_SPIRAM_HEAP_SIZE=4194304

# Not working on stable version v4.1 due to the bug:
# https://github.com/zephyrproject-rtos/zephyr/pull/88073
# But works on main branch with patch.
# CONFIG_SPIRAM_RODATA=y
CONFIG_SPIRAM_FETCH_INSTRUCTIONS=y

# LVGL
# ==============================================

CONFIG_LV_DEF_REFR_PERIOD=60

CONFIG_LV_Z_VDB_CUSTOM_SECTION=y
# CONFIG_LV_DRAW_THREAD_STACK_SIZE=32768
# CONFIG_LV_DRAW_LAYER_SIMPLE_BUF_SIZE=32768

CONFIG_LV_Z_MEMORY_POOL_CUSTOM_SECTION=y
# CONFIG_LV_Z_MEM_POOL_SYS_HEAP=y
# LVGL Transform requires a lot of memory
CONFIG_LV_Z_MEM_POOL_SIZE=65536

CONFIG_DISPLAY=y
CONFIG_DISPLAY_LOG_LEVEL_DBG=y

CONFIG_MSPI=y
CONFIG_MSPI_ESP32=y
# CONFIG_MSPI_LOG_LEVEL_DBG=y

# TODO: NXP Added their own driver for the CO5300 display
# Review if it makes sense to move to NXP driver
CONFIG_ELCO5300=y

CONFIG_INPUT_CST92XX=y
# CONFIG_INPUT_CST92XX_EV_DEVICE=y
CONFIG_INPUT_CST92XX_INTERRUPT=y
CONFIG_INPUT_QUEUE_MAX_MSGS=40
# CONFIG_INPUT_LOG_LEVEL_DBG=y

# CANBus
# CONFIG_CAN_MAX_FILTER=8
CONFIG_CAN_MCP251XFD_INT_THREAD_STACK_SIZE=4096

# Bluetooth
# ==============================================

CONFIG_BT=y
# CONFIG_BT_HCI=y
CONFIG_BT_DIS=y
CONFIG_BT_ATT_PREPARE_COUNT=1
# CONFIG_BT_PRIVACY=y
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="EerieLeap"
CONFIG_BT_DEVICE_APPEARANCE=833

# CONFIG_BT_SMP=y
# CONFIG_BT_SMP_SC_ONLY=y
# CONFIG_BT_SMP_APP_PAIRING_ACCEPT=y
# CONFIG_BT_SMP_LOG_LEVEL_DBG=y

# "BT RX WQ" thread
CONFIG_BT_RX_STACK_SIZE=4096
# "BT LW WQ" thread
# CONFIG_BT_LONG_WQ_STACK_SIZE=2048

# CONFIG_BT_LOG_LEVEL_DBG=y

CONFIG_BT_GATT_SERVICE_CHANGED=y

CONFIG_BT_MAX_CONN=1
CONFIG_BT_MAX_PAIRED=1

CONFIG_BT_BUF_ACL_TX_COUNT=12
CONFIG_BT_CONN_TX_MAX=12
CONFIG_BT_BUF_EVT_RX_COUNT=16
CONFIG_BT_L2CAP_TX_BUF_COUNT=12
# CONFIG_ESP32_BT_RESERVE_DRAM=y
# CONFIG_ESP32_BT_LE_HCI_INTERFACE_USE_RAM=y

# Data Length Update
CONFIG_BT_USER_DATA_LEN_UPDATE=y
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_L2CAP_TX_MTU=247
