CONFIG_FLASH_SIMULATOR=y
CONFIG_GPIO_EMUL=y

CONFIG_DISPLAY=y
CONFIG_INPUT=y

# Memory
# 8MB SRAM
CONFIG_SRAM_SIZE=8388608
# 2MB Heap
CONFIG_HEAP_MEM_POOL_SIZE=2097152
CONFIG_LV_Z_MEM_POOL_SIZE=1048576

# Bluetooth
# ==============================================

CONFIG_BT=y
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="EerieLeap"
CONFIG_BT_SMP=y
CONFIG_BT_USER_DATA_LEN_UPDATE=y
# BT Settings
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_BT_SETTINGS=y
